# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-18 09:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rfid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfid_nr', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Schüler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vorname', models.CharField(max_length=50)),
                ('nachname', models.CharField(max_length=50)),
                ('klassenstufe', models.IntegerField()),
                ('klassengruppe', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Zeit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeit', models.DateTimeField()),
                ('schüler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anmelden.Schüler')),
            ],
        ),
    ]
