# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-18 09:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anmelden', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schüler',
            name='rfid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='anmelden.Rfid'),
            preserve_default=False,
        ),
    ]
