# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-18 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anmelden', '0002_schüler_rfid'),
    ]

    operations = [
        migrations.AddField(
            model_name='schüler',
            name='anwesend',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
