# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-20 15:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anmelden', '0003_schüler_anwesend'),
    ]

    operations = [
        migrations.AddField(
            model_name='zeit',
            name='datum',
            field=models.DateField(default=datetime.date(2018, 3, 20)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='zeit',
            name='zeit',
            field=models.TimeField(),
        ),
    ]
